# .streamlit/secrets.toml

private_gsheets_url = "https://docs.google.com/spreadsheets/d/1dWJ9P699hTt7doVeJoy8JlniqyGIpuhrIOQGbI3-M70/edit#gid=1846716379"

[gcp_service_account]
type = "service_account"
project_id = "review-ty"
private_key_id = "eeab580b08fd0a77bc957166dead353d31a21b65"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCkYImmAprIeNUs\n7d++DU4FaYg4YCrIup6c65JGB1b8uc2/Ti9sZIl3bO4RVcl9h8ux3k6mY9t3Ddoh\neoR5ZAhSFFSg4un5fQh8G9a2WNgTOCnHRpHLmqqOZZLElFAwrWFM6S5aO7+osQ25\n61Qi/ad8wTonL2Z6rg/zxkaKUABZFL28sZSRyQOn6FysdOuQ3yw+dgzidEqGEvzC\nstx/RD/psX3tVldHCwZEFMOO02TjVw5vwGHmLL20h8R3a9osxh/X753QOi44+jfg\nQQfcK/CrbqlCOPqdiavJIyUflt9fvsLOyiMZP23f7rnWjIIT+EyIflM81Fiv6NkH\nj3qEpLa9AgMBAAECggEADTvRcSpWBExIG1cmU4J2NNTXePRzFViC8w67JsSqAexC\njoOQqVkZwSHls8MUlvTjFxWW/uncriPRGy9mMXC2g8crvg0uuZ2RnI5QNbuG39s+\nb9L0Y3A3CYJPc+Cd6SFYS00dpHmZd08T1BNIYY3K2W4kDKoSBc/0LFPa84E32fQC\nvqwwcUY6fJ1xx3y80O0QM6kuwPqwY2+VRBtEX3/vZfFPkvkqn8rZpJWk/mf+sNn+\nmAAoLUC6GeUD86N1TnNb6mw33rkFNhkGLrYJtqQoEy0I68qFkKDaJRU1jJ1B5G3I\nzbLWUnJ6i1qzF1eJRf7GT1uTg5bbmqWcE+C9yWTCKQKBgQDQYET5Fgj62Yx32m7J\n5XEPDrg7df95dO6K3wEMFUtNhh267WylmamwyCRDoTNdAp6V8AA0Sv7NKVa0UK/H\nqEtSEYvpx8bNOUcdBYbwomeWLELgOrYhyHHvE8EP/bejsdMWqpG+JlttKTcXXrKl\nVR3ozOb50OzxowuwGVcKgz4OlQKBgQDJ8fbFy0PWKNazikyp89Ooodo0vB2cEND1\nJjNpAaD8fKbK6Bo7nqGvkDsYJ7QKT6zdd8siiThIBKRXHY6HCoGaXgF8aJKg57g7\n/moP0Vj+edQeSUUKVs0Ne/SavSGL69jPuBaTS5HANyXyKLvusjYjDNSGt+dLznIR\nHswMrg4FiQKBgFOnMkllJTm/eHrtQCjhaaAH4sJMPsG9xb4OhNca/V4kB29xvXpF\n1C/aSWS1JG+ki5HaBdr4eI5YmCxPcCIRWBucW7UAtLjS08+81k1ohXluT3LBXzj0\nxXibT5hh3QVkcD/bPiM+Ntn9/9Xr+IATSayaBegojdb8A8cwhRb9VT55AoGAPXPD\nG2eCah4dT59LOwB2rT8rbpa8D+zSGXeZd1/GhG7ONrqwmOnp28nxIaWbVPPv76jv\niL/m/4tiExxsbc2VqMroeto7nHlHCAKgddXH1hBuqxSyzLWjSnIo+hmJptGLNZKY\nVBRP8wUVJ/6bScSzUrEpzyERYnEdJvaPM2CX5bkCgYA627oAkU1kdL7DolxNKR4P\nseiPc+DGRapYC2eifom5F6QCXRFlw0nJM/OpPaF3azPC7hI77lZGup0U9Hw07JeQ\nXRzrjfqB65PGMhrsNmM2wR1nJKV1Urlg9oUdH7CJwEXZxRjqHv2g4nHoAqxcQ8Hb\n6RoKEGPFjmf7dtIvtPhijg==\n-----END PRIVATE KEY-----\n"
client_email = "vibey-data-analysis@review-ty.iam.gserviceaccount.com"
client_id = "111085449530142952270"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vibey-data-analysis%40review-ty.iam.gserviceaccount.com"

[mongo]
host = "13.213.52.14"
port = 27017
username = "admin"
password = "admin"

[postgres]
host = "13.213.52.14"
port = 5432
dbname = "test"
user = "admin"
password = "1234"